language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./tests/run-tests.sh

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
